### ISSUE TITLE
Burndown chart

### ISSUE THREAD

**Issue by LukeStrazz** [LukeStrazz/VitalVues#10]
Create burndown chart for project. Link URL of chart when finished with first week.

**Comment by emely009** [comment]
https://lucid.app/lucidspark/0c9eb3c9-b1f8-4a18-9c6f-87f09ec610fd/edit?view_items=yRbVNctaJzbQ&invitationId=inv_857c7fc2-2c27-4170-8dfa-d17c7c8bc41b
