### ISSUE TITLE
Notifications - SMS - Email - Dashboard

### ISSUE THREAD

**Issue by furkanxny** [LukeStrazz/VitalVues#20]
Users need to be able to get text messages and emails for various reminders being made.

Acceptance criteria:
SMS and Email messages are able to be sent and read.

**Comment by JustinWhite17** [comment]
Created Maligun account using school email 
Created API Key
Added builder into main
Added controller: NotificationController
Added a route trigger right after app.UseEndpoints
Donwloaded postman to test API

**Comment by LukeStrazz** [comment]
Ensure contact form is visually appealing, use: https://codepen.io/joanasesinando/pen/gOrrNMj
