### ISSUE TITLE
Workout Schedule

### ISSUE THREAD

**Issue by emely009** [LukeStrazz/VitalVues#24]
TODO after epic: https://github.com/users/LukeStrazz/projects/2/views/1?pane=issue&itemId=79181555

Ensure Users are able to add and remove workouts from their schedule.

Acceptance criteria:
CRUD operations.

**Comment by furkanxny** [comment]
Required .cs files created and workout html template created.

**Comment by furkanxny** [comment]
Users are able to add and remove workouts from their weekly schedule. Styling and error handling have been added.
