### ISSUE TITLE
Use AI Chat to create goals

### ISSUE THREAD

**Issue by furkanxny** [LukeStrazz/VitalVues#36]
TODO after epic:  https://github.com/users/LukeStrazz/projects/2/views/1?pane=issue&itemId=79183052

Ensure GPT can output achievable initial goal, diet, and workout plan.

Acceptance criteria:
Users can get help from GPT to create their initial goal, diet, and workout plan for healthy head start.

**Comment by LukeStrazz** [comment]
Closing this, not needed
