### ISSUE TITLE
Journal/ personal tracker

### ISSUE THREAD

**Issue by furkanxny** [LukeStrazz/VitalVues#37]
TODO after epic: https://github.com/users/LukeStrazz/projects/2/views/1?pane=issue&itemId=79183285

Users should be able to create journal entries, and view past entries on their health journey. 

Acceptance criteria
Users can see their past journals, update the contents, delete journals, and have a record of their weight or other goals of this date.

**Comment by LukeStrazz** [comment]
Journal: 
Take a list of for example blood works, and put them in a multiselect to add to a journal. Do this for every List in the JournalViewModel.

**Comment by furkanxny** [comment]
Users are able to create and view journals.
