### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by LukeStrazz** [LukeStrazz/VitalVues#7]
Goals scaffolded - Interface, service controller and view has been made to use view model (GoalViewModel in Services project.)

Goal: Have view display goals, with ability to perform CRUD operations.

Acceptance criteria: Goals can be made, edited, shown and have the ability to mark as resolved.

Will link to notifications, as encouragement to keep up the process.

**Comment by LukeStrazz** [comment]
Goals scaffolded - Interface, service controller and view has been made to use view model (GoalViewModel in Services project.)

Goal: Have view display goals, with ability to perform CRUD operations. 

Acceptance criteria: Goals can be made, edited, shown and have the ability to mark as resolved. 

Will link to notifications, as encouragement to keep up the process.

**Comment by furkanxny** [comment]
-Users can now create and resolve goals.

-Already existing goals are displayed in the goal page.

-Progress bar feature will be added to each existing goal for visually representation purposes.

**Comment by furkanxny** [comment]
-Added progress bar based on goal start and end dates

**Comment by furkanxny** [comment]
Goals are now editable. Dates are not stored in the database in the required format for some reason.

**Comment by furkanxny** [comment]
Resolve issue where data was not being stored in the database.

**Comment by LukeStrazz** [comment]
Please ensure the page reloads after all goal actions.

**Comment by furkanxny** [comment]
Page reloads after all goal actions. Notifications will be implemented to goals.

**Comment by furkanxny** [comment]
Style sheet for Goals has been added.

**Comment by furkanxny** [comment]
Styling, modal, and error handling added.
