### ISSUE TITLE
Create/ scaffold UI/ UX

### ISSUE THREAD

**Issue by LukeStrazz** [LukeStrazz/VitalVues#8]
UI/UX : https://app.moqups.com/fh09dMNWNutiATLOjDXQK1P2bf9jf5ZS/view/page/ad64222d5 

See: Drive with list of wanted features for project. Determine and create logo for project, and UI/ UX for the site (besides login page.)

**Comment by furkanxny** [comment]
UI/UX have been created https://app.moqups.com/fh09dMNWNutiATLOjDXQK1P2bf9jf5ZS/view/page/ad64222d5
