### ISSUE TITLE
Entity Diagram

### ISSUE THREAD

**Issue by LukeStrazz** [LukeStrazz/VitalVues#9]
Create Entity diagram from VVData project -> Models. 

Trackable entry, Person, Goals at the moment. Comment link of URL to find the ERD diagram.

**Comment by emely009** [comment]
https://lucid.app/lucidchart/1186f989-7222-435d-a1a2-1cf8d1b3d7da/edit?viewport_loc=-132%2C1640%2C1015%2C1357%2C0_0&invitationId=inv_fadadb69-0892-407c-92f2-db28ca80b996
